#!/bin/bash
# Full verification workflow: Build → Deploy → Test

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     JOBFIT AUTO-VERIFICATION LOOP                          ║"
echo "║     Build → Deploy → Verify                                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

BUILD_ID=$(git rev-parse --short HEAD)
FULL_SHA=$(git rev-parse HEAD)

echo "📦 BUILD INFORMATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Build ID (short):  $BUILD_ID"
echo "Build ID (full):   $FULL_SHA"
echo "Commit Message:    $(git log -1 --pretty=%B | head -1)"
echo "Branch:            $(git rev-parse --abbrev-ref HEAD)"
echo "Date:              $(date)"
echo ""

echo "🔍 STEP 1: VERIFY BUILD PUSHED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash .claude/verify-deployment.sh
echo ""

echo "🚀 STEP 2: DEPLOYMENT REQUIRED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ Waiting for manual deployment..."
echo ""
echo "Please deploy build: $BUILD_ID to production"
echo "Then confirm deployment by responding with:"
echo "  ✅ Build deployed and live"
echo ""

echo "✅ STEP 3: VERIFICATION CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once deployment is confirmed, test these features:"
echo ""
echo "📋 ASSESSMENT PAGE:"
echo "   - Open assessment from dashboard"
echo "   - Verify Overview tab shows all sections"
echo "   - Check debug panel shows resume count"
echo ""
echo "📋 TAILORED RESUME:"
echo "   - Go to Tailored Resume tab"
echo "   - Verify it shows 'Using Recommended Resume' (no dropdown)"
echo "   - Click Generate → verify output appears"
echo ""
echo "📋 COVER LETTER (3 Tones):"
echo "   - Go to Cover Letter tab"
echo "   - Select Professional → Generate → Verify"
echo "   - Select Enthusiastic → Generate → Verify"
echo "   - Select Warm → Generate → Verify"
echo ""
echo "📋 APPLICATION QUESTIONS:"
echo "   - Go to Application Questions tab"
echo "   - Add question: 'Tell us about your experience'"
echo "   - Verify question appears on screen"
echo "   - Verify answer appears below"
echo "   - Add another question to test twice"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Report results in format:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Build: $BUILD_ID"
echo "Deployment: ✅ Live"
echo "Assessment: ✅ PASS"
echo "Tailored Resume: ✅ PASS"
echo "Cover Letter (Pro): ✅ PASS"
echo "Cover Letter (Enthusiastic): ✅ PASS"
echo "Cover Letter (Warm): ✅ PASS"
echo "App Questions: ✅ PASS"
echo ""
echo "Issues: None"
echo ""
